name: Check for uncommitted dist/ changes

on:
  workflow_dispatch:
    inputs:
      update:
        description: Commit & Push the dist folder, if there was changes.
        required: false
        default: "true"
  push:
    paths-ignore:
      - "**.md"
  pull_request:
    types: [opened, synchronize]
    paths-ignore:
      - "**.md"

jobs:
  check-dist:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: Install dependencies
        run: bun install

      - name: Rebuild the dist/ directory
        run: |
          bun run build

      - name: Compare the expected and actual dist/ directories
        run: |
          if [ "$(git diff --ignore-space-at-eol dist/ | wc -l)" -gt "0" ]; then
            echo "Detected uncommitted changes after build.  See status below:"
            if [ "${{ inputs.update }}" ]; then
              echo "Publishing dist/ directory."
              git add dist
              git commit -m "chore: updated dist directory"
              git push
            else
              echo "Not publishing dist/ directory."
              git diff
              exit 1
            fi
          fi
        id: diff

      - uses: actions/upload-artifact@v4
        if: ${{ failure() && steps.diff.conclusion == 'failure' }}
        with:
          name: dist
          path: dist/
